resolver: ghc-8.7
allow-newer: true
extra-deps:
  - ansi-terminal-0.8.1
  - ansi-wl-pprint-0.6.8.2
  - colour-2.3.4
  - mintty-0.1.2
  - optparse-applicative-0.14.2.0
  - transformers-compat-0.6.2
packages:
  - asterius
  - binaryen
  - ghc-toolkit
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.7.20180924:
        url: https://ci.appveyor.com/api/buildjobs/u4xad1iq4w7c3fi4/artifacts/ghc/ghc-bindist/ghc-8.7.20180924-x86_64-unknown-mingw32.tar.xz
        sha256: 5a155d470b2d9683042de2272e731b98110411f22f7a75a84b9fd7b9153ed88f
    linux64:
      8.7.20180924:
        url: https://1690-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.7.20180924-x86_64-unknown-linux.tar.xz
        sha256: 50ea100dc414a90e44df15e7400d4c4f7c2b6fe23763ac214b7589fa971380c2
